[build-system]
build-backend = 'setuptools.build_meta'
requires = [
  "setuptools>=67.1",
  "setuptools_scm>=7.1",
]

[tool.setuptools_scm]
write_to = "src/devpi_process/version.py"
write_to_template = """
\"\"\" Version information \"\"\"

__version__ = "{version}"
"""

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
known_first_party = ["devpi_process"]

[tool.flake8]
max-complexity = 22
max-line-length = 120
unused-arguments-ignore-abstract-functions = true
noqa-require-code = true
dictionaries = ["en_US", "python", "technical", "django"]
ignore = [
  "E203", # whitespace before ':'
]

[tool.pep8]
max-line-length = "120"
